// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mr_XL_Graduation.Data;

#nullable disable

namespace Mr_XL_Graduation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mr_XL_Graduation.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mr_XL_Graduation.Models.Admin", b =>
                {
                    b.HasBaseType("Mr_XL_Graduation.Models.User");

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Username = "Admin",
                            IsAdmin = true,
                            Password = "AQAAAAIAAYagAAAAEArwNtgxhOuMd8+jFurQb1fODJRe2PS6w09B2nsgtexlU62p5RfIvuxkCVFGFqLfNg==",
                            AdminId = "1999000001"
                        });
                });

            modelBuilder.Entity("Mr_XL_Graduation.Models.Student", b =>
                {
                    b.HasBaseType("Mr_XL_Graduation.Models.User");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Student");

                    b.HasData(
                        new
                        {
                            Username = "Mr_xl",
                            IsAdmin = false,
                            Password = "AQAAAAIAAYagAAAAEP1qFMKAvnjdbD+BzPNlFRXf42PO38gbCmsO99yQwEjurvTlGyorI6yBbTKti5uu7w==",
                            Balance = 0m,
                            Course = "Computer Science",
                            Email = "mr_XL@example.com",
                            FullName = "Abdulrahman Alkayail",
                            StudentId = "0000000000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
